/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "clave.h"


void
clave_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	enum clnt_stat retval_2;
	int result_2;
	int set_value_1_arg1;
	char *set_value_1_arg2;
	int set_value_1_arg3;
	double_array set_value_1_arg4;
	enum clnt_stat retval_3;
	get_value_result result_3;
	int get_value_1_arg1;
	/*enum clnt_stat retval_4;
	int result_4;
	int modify_value_1_arg1;
	char *modify_value_1_arg2;
	int modify_value_1_arg3;
	double_array modify_value_1_arg4;
	enum clnt_stat retval_5;
	int result_5;
	int delete_key_1_arg1;
	enum clnt_stat retval_6;
	int result_6;
	int exist_1_arg1;*/

#ifndef	DEBUG
	clnt = clnt_create (host, CLAVE, CLAVE_V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = init_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

	set_value_1_arg1 = 1;
	set_value_1_arg2 = "Hola";
	set_value_1_arg3 = 3;	
	set_value_1_arg4.double_array_val = (double *) malloc(3 * sizeof(double));
	set_value_1_arg4.double_array_len = 3;
	set_value_1_arg4.double_array_val[0] = 1.0;
	set_value_1_arg4.double_array_val[1] = 2.0;
	set_value_1_arg4.double_array_val[2] = 3.0;
	retval_2 = set_value_1(set_value_1_arg1, set_value_1_arg2, set_value_1_arg3, set_value_1_arg4, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	printf("Set value\n");

	get_value_1_arg1 = 2;
	
	
	result_3.value1 = malloc(256 * sizeof(char)); // Asigna memoria para value1
	result_3.V_value2.double_array_val = (double *)malloc(32 * sizeof(double)); // Asigna memoria para el array
	memset(&result_3, 0, sizeof(result_3)); // Inicializa la estructura

	retval_3 = get_value_1(get_value_1_arg1, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	//free(result_3.V_value2.double_array_val);

	/*retval_4 = modify_value_1(modify_value_1_arg1, modify_value_1_arg2, modify_value_1_arg3, modify_value_1_arg4, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = delete_key_1(delete_key_1_arg1, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = exist_1(exist_1_arg1, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	clave_1 (host);
exit (0);
}
