/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "clave.h"

typedef struct Tupla {
    int clave;
    char *valor1; // Máximo de 255 caracteres + 1 para el carácter nulo de terminación de cadena
    int N;
    double *valor2;
    struct Tupla *siguiente;
} Tupla;

typedef struct Tupla * List;

List l = NULL;
bool_t
init_1_svc(int *result, struct svc_req *rqstp)
{
	bool_t retval;

	while (l != NULL) {
        List temp = l;
        l = (l)->siguiente;
        free(temp->valor2);
        free(temp->valor1);
        free(temp);
    }
    l = NULL;

    int n = 0;
    retval = TRUE;
    *result = n;
    printf("---------------------Lista inicializada--------------------\n");
    printf("\n\n"); // Agregar una línea en blanco
    return retval;
}

bool_t
set_value_1_svc(int arg1, char *arg2, int arg3, double_array arg4, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

bool_t
get_value_1_svc(int arg1, get_value_result *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

bool_t
modify_value_1_svc(int arg1, char *arg2, int arg3, double_array arg4, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

bool_t
delete_key_1_svc(int arg1, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

bool_t
exist_1_svc(int arg1, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

int
clave_valor_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
